### ISSUE TITLE
🎨 Sub-task: Implement Dark Mode theme

### ISSUE THREAD

**Issue by jezweb** [jezweb/js-gravity-forms-embed#27]
## Description
Implement the Dark Mode theme for embedded forms as part of #26.

### Color Palette
- Background: #1a1a1a
- Form background: #2d2d2d
- Input background: #3a3a3a
- Text: #e0e0e0
- Borders: #4a4a4a
- Primary accent: #4a9eff
- Success: #4ade80
- Error: #f87171

### Key Features
- High contrast for readability
- Subtle borders for element separation
- Hover states with slight lightening
- Focus states with colored outlines
- Accessible color contrast ratios

## Implementation Tasks
- [ ] Add `dark` theme CSS to `get_theme_css()`
- [ ] Include hover and focus states
- [ ] Add transitions for smooth interactions
- [ ] Ensure proper contrast ratios (WCAG AA)
- [ ] Test with light background containers
- [ ] Add dark mode specific error/success styling

## CSS Example
```css
.gf-embedded-form.theme-dark {
    --gf-bg-primary: #1a1a1a;
    --gf-bg-secondary: #2d2d2d;
    --gf-text-primary: #e0e0e0;
    --gf-border-color: #4a4a4a;
    
    background: var(--gf-bg-secondary);
    color: var(--gf-text-primary);
}
```

## Acceptance Criteria
- [ ] All form elements properly styled
- [ ] Maintains readability on dark backgrounds
- [ ] Accessible contrast ratios
- [ ] Smooth transitions on interactions
- [ ] Works with all field types

Related to #26
