### ISSUE TITLE
🎨 Sub-task: Implement Bootstrap-style and Tailwind-style themes

### ISSUE THREAD

**Issue by jezweb** [jezweb/js-gravity-forms-embed#28]
## Description
Implement themes that mimic Bootstrap 5 and Tailwind CSS styling without requiring the actual frameworks, as part of #26.

### Design Specifications
- Border radius: 0.375rem (6px)
- Input padding: 0.375rem 0.75rem
- Border color: #ced4da
- Focus border: #86b7fe
- Focus shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25)
- Primary button: #0d6efd
- Font: system font stack

### Key Bootstrap Elements to Mimic
- Form controls (.form-control styling)
- Button styling (.btn, .btn-primary)
- Form labels and help text
- Validation states
- Input groups styling

### Design Specifications
- Border radius: 0.375rem (rounded-md)
- Input padding: 0.5rem 0.75rem (py-2 px-3)
- Border color: #d1d5db (gray-300)
- Focus border: #3b82f6 (blue-500)
- Focus ring: 2px offset
- Primary button: #3b82f6
- Clean, minimal shadows

### Key Tailwind Elements to Mimic
- Default form input styling
- Focus states with ring
- Button with hover states
- Clean typography
- Utility-first inspired spacing

## Implementation Example
```css
/* Bootstrap-style */
.gf-embedded-form.theme-bootstrap input[type="text"] {
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    background-color: #fff;
    border: 1px solid #ced4da;
    border-radius: 0.375rem;
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}

/* Tailwind-style */
.gf-embedded-form.theme-tailwind input[type="text"] {
    padding: 0.5rem 0.75rem;
    font-size: 0.875rem;
    line-height: 1.25rem;
    color: #111827;
    background-color: #fff;
    border: 1px solid #d1d5db;
    border-radius: 0.375rem;
    transition-property: background-color, border-color, color, fill, stroke, opacity, box-shadow, transform;
    transition-duration: 150ms;
}
```

## Important Notes
- **No framework dependencies** - Pure CSS mimicking the appearance
- Must work standalone without Bootstrap or Tailwind installed
- Should feel familiar to users of these frameworks
- Maintain consistent naming to avoid confusion

## Acceptance Criteria
- [ ] Bootstrap-style theme matches Bootstrap 5 appearance
- [ ] Tailwind-style theme matches Tailwind defaults
- [ ] Both themes work without framework dependencies
- [ ] All form elements properly styled
- [ ] Responsive behavior maintained
- [ ] Focus and hover states implemented
- [ ] Validation states styled appropriately

Related to #26
