### ISSUE TITLE
Refactor existing themes to use CSS custom properties

### ISSUE THREAD

**Issue by jezweb** [jezweb/js-gravity-forms-embed#41]
## Description
Convert all 10 existing themes to use CSS custom properties (CSS variables) instead of hardcoded values, enabling dynamic theme customization.

## Current State
All themes in `class-gf-js-embed-styling.php` use hardcoded CSS values for colors, fonts, spacing, etc.

## Acceptance Criteria
- [ ] All 10 themes converted to use CSS variables
- [ ] No visual changes to existing themes (pixel-perfect backward compatibility)
- [ ] CSS variables follow consistent naming convention
- [ ] All themes work with existing embed system
- [ ] Performance impact is minimal

### CSS Variables to Implement
**Colors:**
- `--gf-primary-color`
- `--gf-secondary-color`
- `--gf-background-color`
- `--gf-text-color`
- `--gf-border-color`
- `--gf-button-bg`
- `--gf-button-text`
- `--gf-error-color`
- `--gf-success-color`

**Typography:**
- `--gf-font-family`
- `--gf-font-size`
- `--gf-font-weight`
- `--gf-line-height`

**Spacing:**
- `--gf-field-padding`
- `--gf-field-margin`
- `--gf-border-radius`

**Effects:**
- `--gf-box-shadow`
- `--gf-transition`

### Files to Modify
- `includes/class-gf-js-embed-styling.php`
  - Update `get_theme_css()` method
  - Add CSS variable definitions for each theme
  - Replace hardcoded values with `var(--variable-name)`

### Example Transformation
**Before:**
```css
.gf-button {
    background: #333;
    color: white;
    border-radius: 4px;
}
```

**After:**
```css
.gf-button {
    background: var(--gf-button-bg, #333);
    color: var(--gf-button-text, white);
    border-radius: var(--gf-border-radius, 4px);
}
```

## Testing Requirements
- [ ] All themes render identically before and after changes
- [ ] No console errors or CSS warnings
- [ ] Themes work in all supported browsers
- [ ] Performance testing shows no significant impact

## Dependencies
- None (foundational change)

## Related Issues
- Part of Epic #40: Visual Theme Customizer
- Blocks issues for theme customizer interface

## Estimated Effort
Medium (2-3 days)

## Labels
enhancement, css, themes
